woocommerce/woocommerce-gateway-paypal-express-checkout

includes/class-wc-gateway-ppec-settings.php
Fixes the filter that should be true by default to set the 'Sole' param.
Fixes #165.
=> Guest checkout should be enabled by default.

includes/abstracts/abstract-wc-gateway-ppec-paypal-request-handler.php, includes/abstracts/abstract-wc-gateway-ppec.php, includes/class-wc-gateway-ppec-checkout-handler.php, includes/class-wc-gateway-ppec-ipn-handler.php, includes/class-wc-gateway-ppec-plugin.php, includes/class-wc-gateway-ppec-settings.php, includes/class-wc-gateway-ppec-with-paypal.php, includes/functions.php
=> Added IPN handler.

.gitignore, includes/abstracts/abstract-wc-gateway-ppec.php, includes/class-wc-gateway-ppec-client-credential-certificate.php, includes/class-wc-gateway-ppec-client.php, includes/class-wc-gateway-ppec-ipn-handler.php, includes/class-wc-gateway-ppec-plugin.php, languages/woocommerce-gateway-paypal-express-checkout.pot
=> Enable translations.

assets/js/wc-gateway-ppec-frontend-in-context-checkout.js, includes/class-wc-gateway-ppec-cart-handler.php, readme.txt
Turning the modal popup off because it is very buggy. Also adding a new filter which allows developers to turn it on again. Fixes #171
@gedex please review.
=> Turn off modal popup by default. 

readme.txt
Adds dsmithweb, fullysupportedphil to contributors
=> Updated readme.txt with contributors

includes/class-wc-gateway-ppec-admin-handler.php, includes/settings/settings-ppec.php
Also fixes toggle to credential fields if merchant prefers to manually
enter their API credentials.
Resolves #201.
=> Added link to reset current credentials to allow reconnection.

assets/css/wc-gateway-ppec-frontend-cart.css, assets/js/wc-gateway-ppec-frontend-in-context-checkout.js, includes/abstracts/abstract-wc-gateway-ppec.php, includes/class-wc-gateway-ppec-cart-handler.php, includes/class-wc-gateway-ppec-checkout-handler.php, includes/class-wc-gateway-ppec-session-data.php, includes/class-wc-gateway-ppec-settings.php, includes/functions.php, includes/settings/settings-ppec.php
=> Enable PayPal Credit for U.S. merchants

includes/abstracts/abstract-wc-gateway-ppec.php, includes/class-wc-gateway-ppec-checkout-details.php, includes/class-wc-gateway-ppec-checkout-handler.php, includes/class-wc-gateway-ppec-client.php, includes/class-wc-gateway-ppec-gateway-loader.php, includes/class-wc-gateway-ppec-with-paypal-addons.php, includes/class-wc-gateway-ppec-with-paypal.php
=> Added subscription support via reference transaction.

includes/class-wc-gateway-ppec-cart-handler.php
=> Added filter to adjust checkout button URL.

includes/class-wc-gateway-ppec-checkout-handler.php
This fixes issue when guest checkout disabled user is returned to
checkout with an error prompt to fill in password field.
Fixes #172.
=> Handle customer registration in checkout page.

includes/class-wc-gateway-ppec-plugin.php
=> Added plugin action links for docs and settings.

includes/class-wc-gateway-ppec-checkout-handler.php
=> do not use the shipping address if it is set to false.

includes/class-wc-gateway-ppec-checkout-handler.php
@gedex please review. Another issue found while testing bookings.
=> only run the validation on checkout if the gateway is enabled

includes/class-wc-gateway-ppec-plugin.php
Fixes #251
Issue introduced in f7e15ec
=> Fix #251 - fatal error on disabling woocommerce

includes/class-wc-gateway-ppec-checkout-handler.php, readme.txt
=> Add is_admin check before is_main_query

includes/class-wc-gateway-ppec-admin-handler.php, includes/class-wc-gateway-ppec-checkout-handler.php, readme.txt
=> Set txnData regardless of action type

includes/class-wc-gateway-ppec-checkout-handler.php, includes/settings/settings-ppec.php, readme.txt
=> Add option to set billing phone number mandatory

includes/class-wc-gateway-ppec-checkout-handler.php, includes/class-wc-gateway-ppec-client.php, readme.txt
=> Always send shipping requirement to PayPal

includes/class-wc-gateway-ppec-cart-handler.php, includes/settings/settings-ppec.php, readme.txt
=> Option to show/hide checkout on cart page

assets/js/wc-gateway-ppec-generate-cart.js, includes/class-wc-gateway-ppec-cart-handler.php, includes/settings/settings-ppec.php, readme.txt
=> Implement EC button on product page

includes/class-wc-gateway-ppec-checkout-handler.php, readme.txt
=> Properly calculate requiredness of billing phone

includes/class-wc-gateway-ppec-checkout-handler.php, includes/class-wc-gateway-ppec-client.php, includes/class-wc-gateway-ppec-plugin.php, readme.txt
=> Fix noshipping by still checking shipping on products

includes/class-wc-gateway-ppec-admin-handler.php, includes/class-wc-gateway-ppec-checkout-handler.php, readme.txt
=> Change status to completed after capturing

includes/class-wc-gateway-ppec-plugin.php
=> Fix issue by depending only if items need shipping

assets/js/wc-gateway-ppec-generate-cart.js, includes/class-wc-gateway-ppec-cart-handler.php
=> Add logic to enable/disable button for variations form

includes/class-wc-gateway-ppec-admin-handler.php, readme.txt
=> Update order meta with new transaction id

includes/class-wc-gateway-ppec-ipn-handler.php, readme.txt
=> Fix issue by updating order correctly

includes/class-wc-gateway-ppec-client.php, readme.txt
=> Fix error by properly checking zero for floats

includes/class-wc-gateway-ppec-checkout-handler.php
=> Fix issue by properly mapping phone either from PP or WC

includes/class-wc-gateway-ppec-client.php
=> Undefined item issue resolve #314

includes/class-wc-gateway-ppec-client.php, readme.txt
=> Fix issue by rounding numbers

includes/abstracts/abstract-wc-gateway-ppec.php, readme.txt
=> Invoice Prefix should have the ability to be empty

includes/class-wc-gateway-ppec-checkout-handler.php, includes/class-wc-gateway-ppec-with-paypal-addons.php, readme.txt
=> Fix issue by checking if we can use CRUD methods

includes/class-wc-gateway-ppec-checkout-handler.php, readme.txt
=> Populate session token

includes/class-wc-gateway-ppec-plugin.php, readme.txt
=> Makes admin notification dismissible.

assets/js/wc-gateway-ppec-settings.js, includes/abstracts/abstract-wc-gateway-ppec.php, includes/class-wc-gateway-ppec-client.php, includes/settings/settings-ppec.php, readme.txt
=> Add ability to select existing / upload new image(s) for logo / header fields

includes/class-wc-gateway-ppec-checkout-handler.php, readme.txt
=> Fix shipping address override by altering WC flag

changelog.txt, includes/class-wc-gateway-ppec-plugin.php, readme.txt
=> Fix typo in activation hook

changelog.txt, includes/settings/settings-ppec.php, readme.txt
=> Fix Settings: Impossible to open API credentials after saving

changelog.txt, includes/abstracts/abstract-wc-gateway-ppec.php, readme.txt
=> Pass woo return args to ajax

readme.txt
Changes 1.5.1 to 1.5.3 within the readme.txt
=> Updated readme version

changelog.txt, includes/class-wc-gateway-ppec-with-spb.php, readme.txt, woocommerce-gateway-paypal-express-checkout.php
Fixes failing checkout for sites with no addons installed
=> Fix - Failing checkout when no addons are used

.gitignore, package-lock.json, package.json
Fixes https://github.com/woocommerce/woocommerce-extension-release/issues/22
* Add dot org release config
=> Add dot org config

includes/settings/settings-ppec.php
=> Add missing semicolon

includes/class-wc-gateway-ppec-client.php
Fix for #414, based on the way PP Standard adds fees as line items.
Do we have any test suite or anything that this should pass?
=> Fees as line items

changelog.txt, languages/woocommerce-gateway-paypal-express-checkout.pot, package.json, readme.txt, woocommerce-gateway-paypal-express-checkout.php
=> Bump version to 1.6.18

includes/class-wc-gateway-ppec-client.php
This PR passes the WC product SKUs to PayPal through the item number arg. 
For `DoReferenceTransaction` requests this is the `L_NUMBERn` arg (see [docs](https://developer.paypal.com/docs/classic/api/merchant/DoReferenceTransaction-API-Operation-NVP/?mark=doreferencetransaction#payment-details-item-fields)). 
For `SetExpressCheckout` and `DoExpressCheckoutPayment` this is the `L_PAYMENTREQUEST_n_NUMBERm` param (see the docs [here](https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout-API-Operation-NVP/?mark=SetExpressCheckout#payment-details-item-type-fields) and [here](https://developer.paypal.com/docs/classic/api/merchant/DoExpressCheckoutPayment-API-Operation-NVP/?mark=DoExpressCheckoutPayment#payment-details-item-type-fields)).
Create a simple and subscription …
=> Pass the product SKUs to PayPal payment requests

changelog.txt, languages/woocommerce-gateway-paypal-express-checkout.pot, package.json, readme.txt, woocommerce-gateway-paypal-express-checkout.php
* Fix - Upgrade the plugin on plugins loaded rather than on plugin init. PR#682
=> Version 1.6.20

changelog.txt, languages/woocommerce-gateway-paypal-express-checkout.pot, readme.txt, woocommerce-gateway-paypal-express-checkout.php
* Fix - Javascript errors during checkout when the Payment Action is set to Authorize. PR#754
* Fix - Style the Smart Payment Buttons according to the chosen button size setting. PR#753
* Tweak - Change the "or" separator used on the cart page to be consistent with other payment gateways (uppercase and 100% opacity). PR#755
=> Release 2.0.2

changelog.txt, languages/woocommerce-gateway-paypal-express-checkout.pot, readme.txt, woocommerce-gateway-paypal-express-checkout.php
```
= 2.0.3 - 2020-07-01 =
* Fix - Records the proper refunded_amount to _woo_pp_txnData in the database PR#764
* Fix - Redirect customers back to the original page they left on after closing PayPal modal PR#765
* Fix - Preserve horizontal layout style setting when using standalone buttons PR#774
* Fix - Smart payment buttons compatibility with older browsers PR#778
* Tweak - Update the Require Phone Number field description PR#772
* Dev - Make the SDK script args filterable PR#763
```
=> Release 2.0.3

.travis.yml, readme.txt
This replaces instances of main with trunk for the repo per pb0GrA-R4-p2
=> Replace instances of main with trunk
