includes/class-wc-gateway-ppec-cart-handler.php
readme.txt
woocommerce-gateway-paypal-express-checkout.php

This will ensure that the user has to go to checkout page and enter billing details. fixes #179

Disable cart and mini cart direct checkout buttons when shipping is needed

---

includes/class-wc-gateway-ppec-settings.php

Extends to the changes from #166 to the checkout page.  
Fixes #176 
@gedex

Set PayPal Guest Checkout to enabled by default

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-settings.php

Also added magic setter and save.
Based off of `issues/201/credentials-related-overhaul`, so need #202 to be merged first and change the base to `master`.

Rename settings loader to 'load' as the instance already implies.

---

includes/class-wc-gateway-ppec-checkout-handler.php

This change will update customer's shipping address in session based on selected shipping address in PayPal. Also resolves multiple calls to `get_checkout_details` from checkout page for billing and shipping sections.
Fixes #183.
Resolves #219.

Fixed tax not updated according to PayPal shipping address.

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-checkout-handler.php
includes/exceptions/class-wc-gateway-ppec-api-exception.php
includes/functions.php

This change also deprecates wc_gateway_ppec_format_paypal_api_exception,
as it's hard to read for new dev (what this func expects). Better just
to use wc_add_notice and pass the message from exception directly.
Fixes #218.

Fixed uncaught exception and simplify error message retrieval.

---

includes/abstracts/abstract-wc-gateway-ppec-paypal-request-handler.php

It should use `$order->reduce_order_stock()` instead of
`wc_reduce_stock_levels()`. The latter is added in 2.7 or `master` branch.
Fixes #228.

Fix incorrect order's stock reducer.

---

includes/abstracts/abstract-wc-gateway-ppec-paypal-request-handler.php
includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-admin-handler.php
includes/class-wc-gateway-ppec-checkout-handler.php
includes/class-wc-gateway-ppec-client.php
includes/class-wc-gateway-ppec-ipn-handler.php
includes/class-wc-gateway-ppec-with-paypal-addons.php
readme.txt
woocommerce-gateway-paypal-express-checkout.php

Fixes #233 
```
SETUP
- IMPORTANT: You must use a host accessible from the Internet (i.e. not localhost) in order for PayPal chatback/IPN to work
- WP_DEBUG true
- Install and activate the latest WooCommerce 2.7 beta
- Install and activate the Subscriptions extension
- Under wp-admin > WooCommerce > Settings
- Base location: United States (US) - Washington
- Currency: United States Dollar ($)
- Under wp-admin > WooCommerce > Settings > Checkout
- Enable guest checkout: checked
- Under wp-admin > WooCommerce > Settings > Tax > Tax Options
- Prices entered with tax: No, I will enter prices exclusive of tax
- Calculate tax based on: Customer shipping address
- Shipping tax class: Shipping tax class based on cart items
- Rounding: unchecked
- Additional tax classes: Reduced rate (first line), …
```

Fix WooCommerce 2.7 compatibility, address pass back

---

includes/settings/settings-ppec.php

Based on feedback from PayPal, this PR adds text the tooltips for the "PayPal Credit" and "Billing Addresses" settings, to assist the merchant.
@roykho

Adds to the description text for the PayPal Credit and Billing Addresses settings, to be more informative.

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-checkout-handler.php
includes/class-wc-gateway-ppec-client.php

Fixes #234 
- 3.0 compatibility fixes concerning POSTed data
- Carts that don't require shipping won't fail to check out when postcode is not provided
- Registration presents and works correctly on final order screen
```
- With 2.6 and 3.0
- With WP_DEBUG true
Note Concerning API Credentials
- Log in to your Sandbox and go to the Test Accounts list at https://developer.paypal.com/developer/accounts/
- You will want to use a BUSINESS or BUSINESS Pro from this list, or make a new one
- Click on the arrow to the left of it to expand options below it and then click on Profile
- On the Account Details modal that appears, click on the API Credentials tab
Test Case 1 Setup
- wp-admin > Settings > Accounts
- Check “Enable customer registration on the Checkout page”
- Uncheck “Automatically …
```

Fix 3.0 compatibility, including registration handling

---

includes/class-wc-gateway-ppec-checkout-handler.php
readme.txt
woocommerce-gateway-paypal-express-checkout.php

Fixes #250 
To Test:
* Enable and set up the gateway, including enabling it on checkout
* Add an item to the cart
* Ensure the gateway presents on both the cart and checkout pages
* Add a coupon to the cart that zeros out the cart
* Ensure the gateway is NOT presented on the cart nor checkout pages

Disable gateway when the cart total is zero

---

includes/class-wc-gateway-ppec-client.php
readme.txt
woocommerce-gateway-paypal-express-checkout.php

Fixes #242 
To test:
- Add an item to the cart
- Add a coupon to the cart
- Verify you are able to complex checkout from the cart using Check Out with PayPal (i.e. that the 10413 does NOT happen)
cc @spraveenitpro @roykho @mattyza @dsmithweb

Fix discount sign change that was dropped in 1.2.0

---

includes/class-wc-gateway-ppec-checkout-handler.php
readme.txt

Concerns #256 
Still having trouble reproducing #256 but this fix does address a way we were #doingitwrong when it comes to un-requiring fields.  See https://github.com/woocommerce/woocommerce/blob/25747f8fc70278014eadfcc59468081465ac2404/includes/class-wc-countries.php#L1134
To test:
```
- wp-admin > WooCommerce > Settings > Checkout > PayPal Express Checkout
- Enable PayPal Express Checkout
- Environment: Sandbox
- Enable the PayPal Mark on Regular Checkout
- wp-admin > WooCommerce > Settings > Checkout
- Enable guest checkout
- Open an incognito window, add a virtual item to the cart and then initiate checkout with PayPal from the cart using a test buyer in the same country as the store's base location. Verify you can complete checkout successfully.  Verify that buyer address …
```

Use the woocommerce_default_address_fields instead to ensure not-required fields stay not-required

---

includes/abstracts/abstract-wc-gateway-ppec-paypal-request-handler.php
includes/class-wc-gateway-ppec-ipn-handler.php
readme.txt

Do not process orders automatically

---

includes/class-wc-gateway-ppec-client.php

The tax amount cannot be negative, use shipping discount in this case for total mismatch workarounds.

use shipping discount instead of tax when adjustment negative

---

includes/settings/settings-ppec.php

Adjusts the description of the 'Billing Address' field, to show revised text and a link to PayPal's technical support.
At PayPal's request, I've adjusted how the description of the "Billing Address" setting is displayed, so we can assist merchants, and share a link to PayPal's technical support. Merchants are having an issue with this field, so it's important that we surface the guiding text as clearly as possible for merchants.

"Billing Address" description adjustments

---

includes/class-wc-gateway-ppec-cart-handler.php

Removing the version string resolves an error that forces a fallback workflow and redirect to paypal.com.
Resolves #280

Do not append version string to checkout.js

---

includes/settings/settings-ppec.php

The `ID` used in the js for the _Enabled/Disabled_ toggle was incorrect. I presume from a _recent_ change, but not had time to look through the plugins history.
Please get this fix merged and deployed to the WP plugin-market asap 😬  🙏 
Closes #325

Fix enabled/disabled toggle's javascript

---

includes/class-wc-gateway-ppec-client.php

This fixes Issue #340. Code changed from **line_subtotal** to **line_total**, because line_total accounts for the amount changes (such as coupon discounts), whereas **line_subtotal** doesn't.

Fix paypal error 10413

---

includes/class-wc-gateway-ppec-plugin.php

LibreSSL forked from OpenSSL 1.0.1g and is therefore > OpenSSL 1.0.1 so
the warning is redundant.
Add check for LibreSSL in OPENSSL_VERSION_TEXT and make non-caputuring
to avoid breaking the version number check

Remove OpenSSL warning when using LibreSSL

---

includes/class-wc-gateway-ppec-client.php

In https://wordpress.org/support/topic/wc-order-numbers-not-going-through-to-paypal/ the user is trying to pass over their custom order ID, but there's no way to do so. I think the order ID should use the same filter used by WooCommerce.

Add support for custom order IDs

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-checkout-handler.php
includes/class-wc-gateway-ppec-gateway-loader.php
includes/class-wc-gateway-ppec-settings.php
includes/class-wc-gateway-ppec-with-paypal-credit.php
includes/class-wc-gateway-ppec-with-paypal.php
includes/functions.php
includes/settings/settings-ppec.php

Fixes #292.
- Refactor checkout methods (code duplication)
- Implement a separate gateway class for PayPal credit (with a separate logo, title)
- Refactor some methods so that they can be used in the context of woocommerce filter

Implement PayPal credit on checkout

---

includes/class-wc-gateway-ppec-client.php
includes/class-wc-gateway-ppec-settings.php
includes/settings/settings-ppec.php

Adds filter `woocommerce_paypal_express_checkout_request_endpoint` (alongside the existing `woocommerce_paypal_express_checkout_request_body`) to be able to relay API requests via another server. This will be used for authenticating API requests on the WCS server. (Context in p7bbVw-2kH-p2.)
Also adds a settings filter — see [precedent in Stripe plugin](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/6d8164689007384cd7178d2d65bdec3a1c2094bb/includes/settings-stripe.php#L6) — in order to be able to disable settings we know won't work with an API Subject lacking non-default permissions.
Let me know if MITM or other security concerns come to mind, though I don't believe this would make anything possible that isn't already.
<s>Marking "in progress" until …

Add hooks for request endpoint and settings

---

includes/class-wc-gateway-ppec-settings.php

Swaps the signature method's being conditional on signature for the certificate method's being conditional on certificate.
In my case, since WooCommerce Services will be proxying the request if credentials are not available (https://github.com/Automattic/woocommerce-services/pull/1254), this change is so that cURL is not configured for a certificate if no credentials are available, which causes the request to an HTTPS server (i.e. https://api-staging.woocommerce.com) to fail.
If there is reason to keep this logic as it is, we can keep looking into other means of forcing the signature credentials or just disabling the cURL certificate.

Default to signature method if certificate missing

---

assets/css/wc-gateway-ppec-frontend-cart.css
includes/class-wc-gateway-ppec-cart-handler.php

If the "Check out with PayPal" [button is shown](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/848031d587a4fe19c85546ee095d59af8daf3d8b/includes/class-wc-gateway-ppec-cart-handler.php#L24) — and it is, if the PPEC gateway [is enabled](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/848031d587a4fe19c85546ee095d59af8daf3d8b/includes/class-wc-gateway-ppec-cart-handler.php#L18) — then we should also enqueue its styles and scripts with no [further condition](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/848031d587a4fe19c85546ee095d59af8daf3d8b/includes/class-wc-gateway-ppec-cart-handler.php#L205).
This change is to remove the latter condition so that the button appears and works normally in the …

Improve cart checkout button appearance in no-linked-account case

---

includes/class-wc-gateway-ppec-plugin.php

The "Settings" link was conditionally removed in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/252 in order to fix an error when WooCommerce wasn't active (https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/251), but also applied to cases in which WooCommerce was active if PPEC was enabled but credentials hadn't been saved:
This PR narrows the condition to the minimum necessary to fix https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/251.

Fix missing Settings link on plugins page

---

includes/class-wc-gateway-ppec-client.php

Reverts the change in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/347 that added an API endpoint URL filter, which didn't end up being used for the purposes that it was intended for.

Revert adding request endpoint filter

---

includes/class-wc-gateway-ppec-checkout-handler.php
readme.txt

* Fix - Prevent filtering if PPEC is not enabled.
* Tweak - Default billing address to be required.
* Add - Hook to make billing address not required `woocommerce_paypal_express_checkout_address_not_required` (bool).

Make billing address not require by default and filterable. Closes #386

---

includes/abstracts/abstract-wc-gateway-ppec.php

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/418
Moves tooltip into `<label>` to catch up with change in WC core help tip styling: https://github.com/woocommerce/woocommerce/commit/d8814f93819a41a64f9f6571542488de8db65dab
Before | After
-- | --

Adjust markup to fix help tip alignment for image settings

---

includes/functions.php
includes/settings/settings-ppec.php

Based on the guidelines in [this doc](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-button/#funding-methods):
1. Adds a USD currency check to the function testing for PayPal Credit support
2. Enables the PayPal Credit option by default
3. Mentions the "Real Money Gaming" restriction in the description

Enable PayPal Credit by default, and restrict its support by currency

---

includes/settings/settings-ppec.php

From the customer's (rather than merchant's) perspective, "Express Checkout" is arguably an implementation detail that they shouldn't need to worry about. This change affects the default user-facing payment method title, simplifying it to "PayPal", in response to this mockup from PayPal:
...and also in light of this code with disables PPEC on regular checkout if the standard "PayPal" gateway is enabled: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/ca9939ee8b5aa42a741ab5f60c795ba916c68567/includes/class-wc-gateway-ppec-checkout-handler.php#L498-L501

Omit 'Express Checkout' portion of default payment method title

---

changelog.txt
includes/class-wc-gateway-ppec-cart-handler.php
readme.txt

Appears when PayPal Credit is not supported and Hide Funding Method(s) multiselect setting is empty, the value for which is encoded as `''` rather than `array()`.
To reproduce issue, select country other than US or currency other than USD so that PayPal Credit is not supported. Save empty selection for "Hide Funding Method(s)" with vertical layout, and observe PHP warning when rendering button on the front-end.
Reported in https://wordpress.org/support/topic/get-warning-when-enable-credit-card-in-express-smart-button/

Fix PHP warning due to incorrect assumption of setting value type

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js
changelog.txt
readme.txt

When the primary 'PayPal Checkout' button – in Smart Payment Buttons mode – is the only one that appears in horizontal layout (default for single product page), the `label: buynow` value we are passing causes the PayPal branding to disappear, unless `branding: true` is also passed. This PR makes sure the latter is passed in every case – it makes no difference in cases when the `label` doesn't appear.
Before | After
-- | --
Addresses feedback in https://wordpress.org/support/topic/paypal-logo-on-new-smart-button/

Fix missing PayPal branding in 'Buy Now' button

---

includes/class-wc-gateway-ppec-gateway-loader.php
includes/class-wc-gateway-ppec-with-spb-addons.php

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/439 (and subscriptions not working in SPB in general).
Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/444
Instead of extending the base abstract class, SPB gateway now extends `WC_Gateway_PPEC_With_PayPal`. **Duplicates** `WC_Gateway_PPEC_With_SPB` code into a separate `WC_Gateway_PPEC_With_SPB_Addons` class (avoiding use of traits to support PHP <5.4), which will no longer be necessary after https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/436.

Modify Simple Payment Button gateway to inherit from existing gateway classes

---

includes/class-wc-gateway-ppec-cart-handler.php

The nonce created with no session will not match the nonce verified when a session is created on AJAX POST. This causes AJAX requests to fail, breaking cart generation and SPB payment from single product pages.
This PR makes sure a session is there by the time the nonce is created. Should address reports of PayPal window closing immediately (https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/438, [forum thread](https://wordpress.org/support/topic/many-bugs-in-1-6-0-version/)).
To reproduce broken payments with Smart Payment Buttons enabled, open single product page in a new session (e.g. Firefox Private Browsing), click the PayPal Checkout button, and see the PayPal window open and immediately close.
To reproduce failed cart generation (with or without Smart …

Fix single product Smart Payment Button failing without existing session

---

assets/css/wc-gateway-ppec-frontend-cart.css
includes/class-wc-gateway-ppec-cart-handler.php

Fixes buttons showing up in the mini-cart when the cart is empty:
Also fixes a JS error any time an empty cart page is loaded.

When cart is empty, don't show mini-cart buttons or attempt to render cart buttons

---

includes/class-wc-gateway-ppec-settings.php

Paypal locale can be different from the site locale, as for example with de_DE_formal where paypal would need de_DE. The filtering of get_locale() being pretty cumbersome because of tons of options, adding a filter seems to be the easiest way.

Add a filter to paypal locale

---

changelog.txt
includes/class-wc-gateway-ppec-checkout-handler.php

Addresses issues #433 
Sets current customer shipping and billing addresses from PayPal session as soon as the PayPal pop-up returns. This is necessary because the PPEC extension allows the customer to select an address in the PayPal pop-up, so the address must be retrieved from there:
Previously, even though the correct shipping address was displayed on the "Confirm your PayPal order" screen, it was not being used by WooCommerce to calculate the taxes. The correct taxes were only calculated at final checkout, so the final charged amount would not always match the confirmation screen.
Now the taxes are calculated from the same address that is displayed on the confirmation screen:

Fix for issue #433

---

includes/class-wc-gateway-ppec-cart-handler.php

Ensures a customer session has been created early enough (for a consistent AJAX nonce) – before scripts are enqueued, at which point headers may have already been sent.
Partially reverts e5c5c47, which fixed the bug on some sites by initializing the session, but on other sites, the header template was being printed before the session could be saved, which was too late for saving the cookie, and so there was a new session (and therefore new nonce) when the AJAX request was processed.
(copied from https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/445:)
Testing the failure case on sites that still have this issue, such as https://jurassic.ninja/ sites:
> To reproduce broken payments with Smart Payment Buttons enabled, open single product page in a new session …

Address invalid nonce due to no customer session in a more robust way

---

changelog.txt
includes/class-wc-gateway-ppec-client.php
readme.txt

Partially addresses https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/474
Should address https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/448 as well
If the customer has entered address data, this will be passed to the checkout form on the PayPal side to prefill the billing address fields (e.g. for the guest checkout flow when a credit card button is clicked).
In particular, this corrects the broken experience on the Checkout screen in which the (required) billing address is requested as part of the PayPal flow, without autofilled values – even after having been entered on the store's Checkout screen.
(Open to refactoring away code duplication, in particular [L681-L695](https://github.com/woocommerce/woocommerce-gateway-paypa …

Provide customer address to PayPal flow even when no order is created

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js
changelog.txt
includes/class-wc-gateway-ppec-cart-handler.php
readme.txt

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/451
Currently, the terms of service checkbox (and the rest of the checkout form's required fields) are validated only after the payment flow is complete, which causes an unnecessary loop in the flow and is too late. This change ensures that form data is sent along with the payment initialization call when a Smart Payment Button is clicked. On the Checkout screen, this triggers form validation on the server, and errors are reported.
Example with empty required fields:
Example with terms of service unchecked:
May be a step towards solving https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/467 (at least for the Smart Payment Buttons case).

Validate checkout form via AJAX upon opening payment flow

---

includes/class-wc-gateway-ppec-cart-handler.php

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/474 – the "name" part, which was not fixed by https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/476 because the customer name is not updated in the session when the address changes.
This PR shares a commit (https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/482/commits/b82d9c95e9ff9c9c98a3a0c6180fe38a7a486503) with https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/475, which passes checkout form data in the AJAX request. Here, it is used to store the complete customer data in the session.
(Also a prerequisite for https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/477.)
To test:
- With …

Store checkout form data in customer session, for pre-filling PayPal form

---

changelog.txt
includes/class-wc-gateway-ppec-client.php
readme.txt

Solves #171 
To test:
1) Create/Edit a product such that it has a description longer than 127 characters. Checkout with PayPal and review logs for a warning message from PayPal:
[L_ERRORCODE0] => 11812
[L_SHORTMESSAGE0] => Invalid Data
[L_LONGMESSAGE0] => The value of Description parameter has been truncated.
[L_SEVERITYCODE0] => Warning
2) Switch to this branch and repeat the test. Your descriptions should be truncated automatically and that warning message should disappear.

Truncate product descriptions to conform to 127-character paypal limit

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-cart-handler.php
includes/class-wc-gateway-ppec-checkout-handler.php
includes/class-wc-gateway-ppec-client.php
includes/class-wc-gateway-ppec-settings.php

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/486
As pointed out in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/486#issuecomment-429113321, removing the filter on `woocommerce_cart_needs_shipping` solves the issue of the missing shipping total (implemented in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/commit/5c3e09856e59d57ffbd639301ddfe941657fee8d).
The filter was originally added so as to not show a shipping address selector on the PayPal checkout screen when starting on the store checkout screen (and having already entered a shipping address). Besides being overly broad, this was not the best way to handle the shipping address, as it affects the `NOSHIPPING` flag rather than …

Properly handle shipping address flag and fix missing shipping total

---

includes/class-wc-gateway-ppec-client.php

This filter is useful to let developers modify details passed to PayPal.
Specially to unset $details['items'] for letting PayPal accept decimal quantities of products (issue #430)

Filter for details sent to PayPal to fix decimal quantities error 10413

---

includes/class-wc-gateway-ppec-admin-handler.php
includes/class-wc-gateway-ppec-checkout-handler.php
includes/class-wc-gateway-ppec-ipn-handler.php
includes/functions.php
readme.txt

Fixes #504 
Test steps:
* if you're using a local site, make sure you're running ngrok
* purchase an item and pay using the PPEC
* log into the merchant dashboard on PayPal and accept the payment - paypal should sand an update to your site containing the fees
* open the order in wp-admin and verify that the fees appear

Display PayPal fees under the totals on the order admin page

---

assets/js/wc-gateway-ppec-generate-cart.js
includes/class-wc-gateway-ppec-cart-handler.php
readme.txt

Fixes #500 
Fixes #467
I've merged both fixes into the same PR because they are very related and the amount of code is still small enough for a single PR.
This PR includes a more complete version of the fix on https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/506.
When making any kind of request to the server, WooCommerce runs this code: https://github.com/woocommerce/woocommerce/blob/897af8d20ef24e58164376ef65d980d2759f5956/includes/class-wc-form-handler.php#L706
If there's a GET/POST variable called `add-to-cart`, it will try to add that product to the cart. The request structure is different from what WC Core expects, so for variable products it won't find the required attributes and it will throw [an …

Fix using the PayPal smart button on a variable product page, or a product with Addons

---

includes/class-wc-gateway-ppec-cart-handler.php

Include `$attributes` in the `add_to_cart` call within `WC_Gateway_PPEC_Cart_Handler::wc_ajax_generate_cart()`. This way variations with "Any" attribute will work correctly.
1. Create a variable clothing product.
2. Add attributes for both color and size.
3. Add individual variations for every size but without specifying colors.
4. Open the product page, select variations and click the PayPal button. Completing the payment is not required.
5. Navigate to the cart and verify that the selected color is actually added to the cart, instead of just the size.
Fixes #522

Keep variation attributes when they are added to the cart

---

includes/class-wc-gateway-ppec-cart-handler.php

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/493#issuecomment-452268356
After landing https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/491, PayPal SPB buttons stopped rendering in the mini-cart.
The problem is that the mini-cart HTML is cached in localStorage in the client, so the code that renders it in the server doesn't always run, so we can't rely on it for enqueuing the PayPal JS files.
I've implemented 2 alternative solutions, this one and #520. Please chime in on which one you prefer.
In this PR, I made sure that the `wc-gateway-ppec-smart-payment-buttons` JS script is loaded whenever the mini-cart widget is rendered, by hooking into the `widget_title` hook.
To test:
* Make sure that the Simple Payment …

Render the PayPal buttons in the mini cart

---

changelog.txt
includes/class-wc-gateway-ppec-client.php
readme.txt

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/517
This bug was fixed in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/341, but it re-appeared in `1.6.6`. This PR fixes the `Error 10413` bug and also keeps the separate "Discount" lines in the PayPal flow.
I'm not sure how to test this since I haven't managed to reproduce it locally. It seems to be related with differences in precision when handling lots of numbers with decimals in the same order (shipping price, taxes, discount coupon, item price...). At the end, somehow the sum of all the parts is different than the total so PayPal fails.
@zanza321 @beehavendesignz I would prefer to be able to reproduce this error at least once before releasing the fix. I'm …

Fix Error 10413 when using coupons

---

includes/class-wc-gateway-ppec-cart-handler.php

Certain themes are applying the `widget_title` filter with fewer than the 3 params [documented](https://developer.wordpress.org/reference/hooks/widget_title/), causing PHP errors and warnings with the 1.6.7 release. This change adds default parameters to prevent this issue.
Can test by adding `apply_filters( 'widget_title', 'Widget Title' );` to your theme's `functions.php` file.
Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/524 and addresses issues in https://wordpress.org/support/topic/string-of-new-php-errors-with-version-1-6-7/

Guard against themes applying filter with too few params

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/527
A change in a recent release of PayPal's checkout.js is incompatible with the `null` value we were passing to `paypal.Button.render` for the `allowed` funding methods, breaking the rendering of the buttons. Passing `undefined` as an alternative works fine.
Can test by loading the Cart page with Smart Payment Buttons and vertical layout enabled: in this branch the buttons should render normally, while in `master` there should be no buttons and a browser console error.
_Edit:_ behavior can also be confirmed on PayPal Checkout's [demo page](https://developer.paypal.com/demo/checkout/#/pattern/vertical): `allowed: null` doesn't work, but `allowed: undefined` does.
This change brings the render call …

Avoid SPB render error by tweaking 'allowed' funding methods' empty value

---

assets/js/wc-gateway-ppec-generate-cart.js
includes/class-wc-gateway-ppec-cart-handler.php

Fixes #534
The changes in this PR also do not regress the fix for #522, fixed originally in #523.
1. Create a product with attributes
2. Go to the single product page, select some attributes
3. Use the 'buy now' button
4. See that the nonce and all other form fields are exposed during and after making the purchase.
What the customer sees during and after the purchas:
What the store owner sees:
What was happening is that we were sending multiple unwanted properties as attributes in the 4th argument to `add_to_cart` call in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/471370c66cd9893120e7572483ae3473ccc9beed/includes/class-wc-gateway-ppec-cart-handler.php#L98
The `$attributes` variable seen there looked like this for a product with attributes:
```
Array ( …
```

Use only product attributes when adding to cart

---

changelog.txt
includes/class-wc-gateway-ppec-plugin.php

It was pretty straightforward to just switch out the option writes for saving to internal values, as mentioned in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/539#issuecomment-474100787. These options were only used in one location, hooked onto `admin_notices`. This PR simply replaces them with class properties.
Testing:
The easiest way to test is to make manual edits in `_check_dependencies()` and `_check_credentials()` to just force the exceptions to be thrown / not thrown. Then just reload the admin and ensure the correct notices show up.
CC @laurendavissmith  / @superdav42

Remove option writes during bootstrap

---

includes/class-wc-gateway-ppec-with-paypal-addons.php
includes/class-wc-gateway-ppec-with-spb-addons.php
includes/class-wc-gateway-ppec-with-spb.php
readme.txt

Fixes #545 
Modifies the Subscriptions tooltip if "Require billing address" option is not set:
Removes PPEC from the available payment methods if the above option is not set and if the cart contains any virtual subscriptions.
To test:
* Verify that the tooltip appears on the settings page
* Create a virtual subscription and a shippable subscription products
* Attempt to checkout the virtual subscription - PPEC buttons should not appear at any point during the checkout
* Attempt to checkout the shippable subscription - PPEC buttons should appear
* Enable the "Require billing address" setting (for testing purposes I edited `woocommerce_ppec_paypal_settings` in `wp_options` in the database)
* The tooltip of the settings page should not show any changes
* Attempting to purchase a virtual …

Better handling of virtual subs when billing address is not required

---

includes/class-wc-gateway-ppec-checkout-handler.php
readme.txt

Fixes #549 
Checks if the shipping address returned from PayPal is not empty before trying to use it to update the customer information.
To test:
* Make sure define( 'WP_DEBUG', true ); is present in wp-config.php
* Attempt to use the checkout button when purchasing any virtual product
* PayPal should not ask for shipping or billing address during checkout
* After returning to the site, no PHP notices should be shown and you should be able to complete the order

Check if the shipping address returned from PayPal is not empty

---

changelog.txt
includes/class-wc-gateway-ppec-checkout-details.php
includes/class-wc-gateway-ppec-checkout-handler.php
readme.txt

(Partially) fixes #561 
The error described in the issue above happens when PayPal does not return any billing details of the customer to the site. It might be a result of an issue in the API, since we weren't able to reproduce it. But we should still prevent the site from blowing up with PHP notices and this PR does that.
To test:
* enable debug logging
* add `return false;` at line 454 in `includes/class-wc-gateway-ppec-checkout-details.php`
* attempt to checkout
* no php errors should be visible when returning from PayPal
* the checkout should still not be possible because the billing fields are required
* there should be a message in the logs `PayPal response did not include the payer billing details` and the response

Prevent PHP errors when no billing details are present in PP response

---

changelog.txt
includes/class-wc-gateway-ppec-checkout-handler.php
readme.txt

Fixes #569 
The billing address fields should remain required when the corresponding option is set in the admin panel.
To test:
* Use a regular merchant account with no address required option set
* Add only virtual products to the cart
* Open the checkout page
* The billing address fields (street, city, postcode) should not be required: <img width="468" alt="Screenshot 2019-05-09 at 15 47 48" src="https://user-images.githubusercontent.com/800604/57462984-d0b67480-7271-11e9-8009-6d811b4f21eb.png">
* Use a merchant with the billing address option enabled (reach out if you need sandbox credentials for such an account) or manipulate the database to force the "Require Billing Address" option to true
* Ensure the option is set
* With virtual products only in the cart, open the checkout page
* …

Require billing address for virtual products when enabled

---

includes/class-wc-gateway-ppec-admin-handler.php

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/573
See https://github.com/woocommerce/woocommerce/issues/23626 and https://github.com/woocommerce/woocommerce/pull/23634 for context.

Make the capture / cancel-auth processes work even if the order is in a custom status

---

changelog.txt
includes/abstracts/abstract-wc-gateway-ppec.php

Should payment fail for whatever reason as well as throw an exception a
hook is added so that third parties can run any routines they need to in
this scenario.
Use case for this change is we want to be able to log on any payment
error (to new relic).
Stripe has a similar hook here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/a23615803579646973ced040cb1d114d9f5a4032/includes/class-wc-gateway-stripe.php#L851

Add hook on payment error.

---

assets/js/wc-gateway-ppec-order-review.js
includes/class-wc-gateway-ppec-checkout-handler.php

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/561
As described in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/561#issuecomment-508274372, there are some broken edge cases around visiting the Checkout screen after a redirect to PayPal. I've reproduced them specifically for the redirect upon receiving a 10486 error, and I'm not sure whether there are other ways to reproduce such issues and/or if all have been addressed, but this is meant to fix the main issue as I've been able to reproduce it.
- https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/commit/7a9877caead9e956317384933c127dfc8852f6a3 adds first name and last name to the fields copied from the shipping address, so that they have …

Avoid broken confirmation screen edge case after 10486 redirect

---

includes/class-wc-gateway-ppec-admin-handler.php

Closes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/585
Small refactor to clarify functionality of auth cancellation action.

Clarify auth cancellation function name

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js

The change in https://github.com/woocommerce/woocommerce/pull/24227 would break the assumption that there is a newly mounted DOM fragment (and therefore an empty Smart Payment Button container) whenever `updated_checkout` is triggered.
The change in this PR is to make sure the `render` function can be called multiple times with a single container node without duplicate SPB renders occurring.
Can be tested by checking out the branch in https://github.com/woocommerce/woocommerce/pull/24227 and modifying a checkout field with the PayPal Checkout payment method selected. Alternatively, `jQuery( document.body ).trigger( 'updated_checkout' )` can be called from the console. In `master`, this would result in multiple sets of buttons, but in this branch there is no additional render.

Check to avoid duplicate Smart Payment Button render

---

includes/class-wc-gateway-ppec-checkout-handler.php

Hi there
For now, Billing Agreement can be used only with WooCommerce Subscription. 
By adding a filter, other people (like me ^^) could easily enable Billing Agreement without need to use WooCommerce Subscription or hard coding the plugin core :/

Add a filter to enable (or disable) Billing Agreement

---

includes/class-wc-gateway-ppec-admin-handler.php

The missing CURRENCYCODE in capture_payment cause a error after payment authorization has been accepted:
WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
[AUTHORIZATIONID] => 2YC66033TH9230743
[TIMESTAMP] => 2019-02-07T11:41:21Z
[CORRELATIONID] => 31a70f4754928
[ACK] => Failure
[VERSION] => 120.0
[BUILD] => 000000
[L_ERRORCODE0] => 10613
[L_SHORTMESSAGE0] => Currency mismatch.
[L_LONGMESSAGE0] => Currency of capture must be the same as currency of authorization.
[L_SEVERITYCODE0] => Error
)
Adding the CURRENCYCODE to params fix the problem.

Add CURRENCYCODE do capture_payment

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js

Avoids costly (150+ ms in my profiler) Smart Payment Button render on every Checkout page load, since the `updated_checkout` event is always called when the order review section is actually ready (after an AJAX request, currently). So, it was always being called one unnecessary time before that.

Skip wasteful render on initial Checkout page load

---

includes/class-wc-gateway-ppec-cart-handler.php

Closes #554 
To test, do something like this:
```
function hello_hide( $hide ) {
if ( function_exists( 'is_product' ) && is_product() ) {
global $product;
$product_name = $product->get_name( 'edit' );
if ( FALSE === stristr( $product_name, 'HIDE' ) ) {
return $hide;
} else {
return true;
}
}
return $hide;	
}
add_filter( 'woocommerce_paypal_express_checkout_hide_button_on_product_page' , 'hello_hide' );
```

Add filter for paypal button on products

---

includes/class-wc-gateway-ppec-checkout-handler.php
languages/woocommerce-gateway-paypal-express-checkout.pot

Fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/609
Uses proper plugin-specific text domain for "create account" strings.
Also regenerates POT file (via `wp i18n make-pot`).

Fix domains for translatable strings

---

languages/woocommerce-gateway-paypal-express-checkout.pot
woocommerce-gateway-paypal-express-checkout.php

A small change to improve the description of the plugin as it appears in the "Installed Plugins" page of wp-admin.
@californiakat, this reads well to me but wanted to check you're still happy with the new description now that you can see it in place?
**To Test**
Navigate to the "Installed Plugins" page and ensure the plugin description matches the proposed test in #605.
Fixes #605.

Improve plugin description

---

changelog.txt
includes/class-wc-gateway-ppec-plugin.php
languages/woocommerce-gateway-paypal-express-checkout.pot
readme.txt

Fixes #578 
We actually already had a notice implemented [here](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/commit/a8a8b56fe739b26f01ddb73420ff200c04c7fcd2):
It was shown if:
* PPEC is enabled
* Smart Payment Buttons are disabled
* `wc_gateway_ppec_spb_notice_dismissed` option is not in the db or is not set to `yes`
I changed the notice to the following to emphasize that the buttons are going away in the next release:
It is still shown if PPEC is enabled but the buttons are disabled, but now it is also red and not dismissible. The only way to get rid of it is to enable Smart Payment Buttons.

Add a notice about legacy payment buttons deprecation

---

changelog.txt
includes/class-wc-gateway-ppec-client.php
readme.txt

Fixes #562 
Fixes #633 
Rounds the `total_item_amount` and `order_total` after applying the discounts.
To test:
1. Add a product with price 89.99
2. Create a coupon with 99% discount
3. Attempt to go through PayPal checkout product from 1. with coupon from 2.
4. The PP window should open and you should be able to complete the checkout
or:
1. Repeat steps 1-2 above
2. Set the number of decimal places to 4
3. Checkout should still work

Fix error 10426 when coupons are used

---

changelog.txt
includes/class-wc-gateway-ppec-cart-handler.php
readme.txt

Fixes #580 
The only way in which I could reproduce this was to add the following filter:
```
add_filter( 'woocommerce_is_rest_api_request', function ( $a ) {
return true;
} );
```
Technically it's possible to add a plugin that modifies the REST paths and leads to this. 
The fix is both to use the same method as WC core is using to check for frontend requests (if REST is detected, then session is set to `null`). The `is_rest_api_request ` method was set to public only in the recent versions of core, so then we fall back to checking if session is not empty/falsey.

Fix call to a member function has_session() on null

---

changelog.txt
includes/class-wc-gateway-ppec-client.php
readme.txt

Fixes #607 
I was not able to reproduce this with any currency-switching plugin. In fact, it looks like the pro version of `WooCommerce Price Based on Country` correctly filters the currency when renewing. So, here are steps to reproduce by manually switching the site currency:
0) You may want to change your PayPal sandbox merchant account settings to automatically allow multicurrency purchases. You can do that by logging in to https://sandbox.paypal.com using your sandbox merchant account. Then go to https://www.sandbox.paypal.com/businessmanage/preferences/payments which is found at Settings Gear Icon > Account Settings > Payment preferences (in the sidebar) > Block payments (click the update link). Select "Yes, accept and convert them to U.S. Dollars." on that page after the JS is …

Use order currency when renewing subscription

---

includes/class-wc-gateway-ppec-checkout-handler.php
includes/class-wc-gateway-ppec-client.php
includes/class-wc-gateway-ppec-with-paypal-addons.php

Fixes #551 
1. Create a subscription
2. Navigate to the subscription in the My Account page.
3. Click 'Change payment'.
4. Select PayPal Checkout
5. See that you are able to update the subscription payment method
- WooCommerce Subscription uses the function `WC_Subscriptions_Change_Payment_Gateway::change_payment_method_via_pay_shortcode` to handle payment changes, with a $0 charge
- This calls `process_payment` in our gateway
- We decide whether or not it's a subscription payment method change in `is_order_changing_payment_method_for_subscription` https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/640/files#diff-825815001892595d50e5e5eaacce96b5R76
- If it's a payment change, in `change_subscription_payment_method()` we send back the array expected by …

Handle subscription payment change

---

includes/class-wc-gateway-ppec-plugin.php

Fixes #639
1. Run the WooCommerce setup wizard (on a fresh Woo install or [manually via the help tab](https://d.pr/i/09iGX9))
2. Make sure the PayPal gateway is selected under the Payment tab
3. Click the continue button
4. See the following error notice:
During the onboarding wizard, WooCommerce calls `WC_Countries->get_default_address_fields()` which PPEC is filtering inside [`WC_Gateway_PPEC_Checkout_Handler::filter_default_address_fields ()`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/a6b4b195cdc41b5b94202d7acc63ad3e8abd4606/includes/class-wc-gateway-ppec-checkout-handler.php#L122)
`filter_default_address_fields` then calls [`WC_Gateway_PPEC_Plugin::needs_shipping()`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/a6 …

Fixes error "Trying to get property of non-object" found during onboarding wizard

---

changelog.txt
includes/class-wc-gateway-ppec-admin-handler.php

Fixes #652.
To reproduce:
1. Install AutomateWoo
2. Install Subscriptions
3. Install AutomateWoo -- Subscriptions Addon
4. Ensure PP Checkout is active
5. Create a new Workflow in AutomateWoo
- Trigger: Subscription Order Paid
- Subscription Order type: Parent
- Action: Trigger Order Action
- Order Action: Generate download permissions
6. Click "Save" to save the workflow.
7. With latest master, this triggers a fatal error:
```
2019-12-20T05:31:57+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on bool in /nas/content/live/seventhrstage/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-admin-handler.php:44
Stack trace:
#0 /nas/content/live/seventhrstage/wp-includes/class-wp-hook.php(288): …
```

Check if order exists before adding order actions

---

includes/class-wc-gateway-ppec-cart-handler.php

Fixes #628 
When one of the products in a product bundle is out of stock, there is an appropriate message in the product page, the "Add to cart" button is not displayed, but the PayPal Smart buttons are displayed.
I have added a check for the stock status of the product before displaying the smart buttons. Though this check is redundant for simple products, for bundled products, this solves the issue.
**Steps to Test**
1. Install the Product Bundles plugin.
1. Create a bundled product BP with component products A,B and C: https://d.pr/i/gYc12o
1. Edit one of the component products and make it out of stock. Look at the product page: https://d.pr/i/fsURy8
1. On master, the Smart buttons are displayed, while on this branch, they are not.
Closes #628

Display smart buttons in product page only if product is in stock

---

includes/class-wc-gateway-ppec-cart-handler.php

Fixes #635 
When a free product with free shipping is in the cart, the smart payment buttons are displayed in the mini cart. PayPal does not allow for zero payment and so these buttons should not be displayed.
I added an additional check for the cart total value not being 0 for displaying the PP buttons in the mini cart.
**Steps to test**
1. Create a product Z that has price set to 0.
2. Create two shipping methods for your region - free shipping and flat rate.
3. Enable Free shipping and disable flat rate shipping.
4. Add a product P that has a price > 0. Check the mini cart. The Smart Payment buttons are displayed.
5. Add Z to the cart. Remove P. Check the mini cart. On master, the Smart Payment buttons are displayed while on this branch, they are not displayed.
6. Disable Free shipping …

If cart total is 0 do not show PP buttons in mini cart

---

changelog.txt
includes/class-wc-gateway-ppec-cart-handler.php

Fixes #469 
Rather than cleaning everything that is passed, this does a check to see if what was passed matches an existing attribute term slug. `wc_clean` will remove all encoded items, so it isn't the best way to handle this, which is mentioned [here](https://github.com/woocommerce/woocommerce/blob/3.4.4/includes/data-stores/class-wc-product-data-store-cpt.php#L1059).
@woocommerce/extendables for review assignment

Global attributes stripped before sent to PayPal if unicode characters

---

includes/class-wc-gateway-ppec-cart-handler.php

Fixes #460 and #478 
The smart buttons are displayed in the single product page of External/affiliate products and grouped product pages. Clicking on the smart button gives an error.
Along the lines of #662 I added a check for the product being of type external or grouped before the smart buttons are displayed.
**Steps to Test**
1. Create an external product EP
2. View the product page. 
3. Apart from the button that is linked to the external site, the PayPal smart buttons are also displayed on master. On this branch, the smart buttons are not displayed.
4. Repeat the above process for a grouped product.
Closes #460 and #478

Do not display smart buttons for external products and grouped products

---

includes/class-wc-gateway-ppec-cart-handler.php

Fixes #497 
A single product page created using the 'product_page' shortcode was not showing the PayPal smart buttons. 
The scripts for showing the smart buttons are enqueued based on several conditions, one of which is whether it is a product page. The `is_product()` function is used for this purpose but this returns false for the page created using shortcode. I added an additional check `$has_product_shortcode` which looks for the `product_page` shortcode in the content of the page.
**Steps to test**
1. Create a page with a product_page shortcode in the content for a particular product id existing in your installation. For example, if you have a product with id 45, then create a page with `[product_page id=45]` as content. Publish it.
2. View this product page. On master you can see …

Check if product_page shortcode is present to find if it is a product page

---

includes/class-wc-gateway-ppec-client.php

After #664, when a coupon is added to the cart with a product having sku, this error was thrown.
Undefined index: sku in /app/public/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-client.php on line 335
I've added a check to see if the sku is set, before adding it as a parameter.
**Steps to test**
1. On 1.7_dev branch, add a product with sku and apply a coupon. Click on the PayPal button. This error is thrown in the debug log.
2. On this branch, this error should not be seen.

Check sku exists before adding it as a parameter

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js
includes/class-wc-gateway-ppec-cart-handler.php
includes/settings/settings-ppec.php

Fixes #572 
The smart payment button can have a label. According to [documentation](https://developer.paypal.com/docs/archive/checkout/how-to/customize-button/?mark=label#label), there are some preset values that can be passed to get one of the available labels.
Currently, all these options are not available as a setting. In addition, the only hardcoded value is set for a horizontal layout only.
I added a button label setting with 4 of the 5 available options(I did not add the `installment` which is specific to two countries only), removed the restriction on vertical layout and passed these settings to PayPal for display on the buttons.
**Steps to Test**
1. On master, in the PPEC settings page, change the layout to Vertical and see that the corresponding PayPal button does not have the …

Add a button label setting for the smart payment buttons

---

includes/class-wc-gateway-ppec-admin-handler.php
includes/class-wc-gateway-ppec-plugin.php

This PR adds an admin notice for sites running a WC version pre 3.0, after they update to 1.6.19 (the next release).
The steps I took to test this are a little complicated since it requires `WC_Version` 2.6.x and you to fake a PPEC plugin update.
1. Created a new site (you could do this on a local dev site but I didn't want to mess anything up).
2. On the site I installed WC 2.6.14 ([download from here](https://github.com/woocommerce/woocommerce/releases/tag/2.6.14))
3. Cloned the PPEC repo into the plugins directory and checked out out this branch.
4. I manually faked the 1.6.19 update by changing the version constant in the main plugin file [here](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/display_wc_pre_30_warning/woocommerce-gateway-paypal-express-c …

Display a WooCommerce pre 3.0 admin notice warning

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-plugin.php
includes/class-wc-gateway-ppec-settings.php
includes/settings/settings-ppec.php

Fixes #579
This PR removes the smart payment button (SPB) option from the PPEC settings page and treats it as enabled by default for all stores.
**changes**
- Inside [`WC_Gateway_PPEC::__construct()`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/2c9bde786cf0ddff47a13d40a891caf15b7c8a59/includes/abstracts/abstract-wc-gateway-ppec.php#L27) and on [`WC_Gateway_PPEC_Settings::load`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/01f18d6734f97a8930528c00573846de686a8772/includes/class-wc-gateway-ppec-settings.php#L88), manually set/override the value of `use_spb` option to be always `'yes'` (this can be filtered to continue using legacy checkout buttons)
- Hide the Smart Payment button option from the settings page
- Remove …

Remove Smart Payment Button setting and treat as enabled by default

---

includes/class-wc-gateway-ppec-client.php

This function didn't do anything (it only defined an unused variable) and hasn't been used by the plugin since it was introduced.
For more details see these comments: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/602#issuecomment-580057785 and https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/603#issuecomment-580091280
1. Add the following code to your site somewhere.
2. You should receive the following error notice.
```php
wc_gateway_ppec()->client->update_billing_agreement( 'B-12352352343' );
``` 
```
PHP Notice:  WC_Gateway_PPEC_Client::update_billing_agreement is <strong>deprecated</strong> since version 1.7.0 with no alternative available. in /app/public/wp-includes/functions.php on line 4651
```
closes #602

Deprecate `WC_Gateway_PPEC_Client::update_billing_agreement()`

---

includes/class-wc-gateway-ppec-plugin.php

This PR moves the upgrade process from plugin init (when WP loads the plugin files) to the `plugins_loaded` hook.
This is to ensure we have access to WC core functions. It also means the plugin is updated at a consistent time, not when WP loads the plugin which can change, and when the dependencies are met. eg WC is active.
This change means: 
1. The plugin version won't update until `plugins_loaded`.
2. The plugin version won't update if the plugin dependencies aren't met. 
1. Disable the WooCommerce plugin.
2. Go into the database and change the `wc_ppec_version` option to 1.6.18. _We need to trick it into running an update. This is fine since the PPEC upgrade script is very minor._
3. Reload an Admin page.
1. On `master` you will get the following error. Note that the plugin version is …

Upgrade the plugin on plugins loaded rather than on plugin init

---

deploy.sh

This is a temporary deploy script. We will revisit the woorelease script at a later date with the intention to improve it so all steps are fully automated. 
This release script is based on a script used to deploy the Robot Ninja Helper plugin. You can find the original source here: https://github.com/woocommerce/robot-ninja-helper/blob/master/deploy.sh 
Some config changes were required for it to work in a PPEC context. eg:
- `PLUGINSLUG`
- `MAINFILE`
- `SVNURL`
- `SVNUSER`
The `svn:ignore` command was also changed to include specific files we need to exclude from deployment. 
`wordpress_org_assets` also needs to refer to the folder which contains the wordpress.org plugin assets which may be different from plugin to plugin.

Add deploy.sh script

---

includes/class-wc-gateway-ppec-settings.php
includes/functions.php

**Issue**: #691 
**A11n only:** See this [Slack thread](https://a8c.slack.com/archives/CJTS771PB/p1583731009099000) for additional context.
This PR ensures stores based in Puerto Rico are eligible for PayPal Credit. Secondly, stores based in the US or Puerto Rico will always map to a US-based locale. 
The locales options by WordPress don't map perfectly to PayPals supported locales (https://developer.paypal.com/docs/archive/checkout/reference/supported-locales/), so I had to do some special mapping. 
Any US-based store with a WP locale that is French, Español or Chinese will map to their PayPal US-based codes. `fr_US`, `es_US`, or `zh_US` respectively. If the store language isn't one of those but is a US-based store it will map to `en_US`.
Any store, located outside of the US or Puerto …

Ensure Puerto Rico and supported Locales are eligible for PayPal Credit

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-checkout-handler.php

**Issue**: #367 
---
As is described on the issue, PPEC would remove itself from the list of available payment gateways if the cart total is $0.
This is because it couldn't previously process $0 orders. This PR also fixes that. 
Like WC Subscriptions Reference Transaction implementation, the order of operations is something like this:
1. Generate an EC token.
2. Redirect the customer off to PayPal.
3. When they complete the process at PayPal, they will be redirected back to the store.
4. We then send a request to PayPal to get the billing agreement token.
It's at this point that PPEC would error as it would then try to process a $0 payment using that billing agreement. 
This PR fixes that by doing something similar to Subscriptions. Once we have the billing agreement, we just need to …

Support subscription initial payments for $0 - free trials, synced etc.

---

includes/class-wc-gateway-ppec-checkout-handler.php

**Issue**: #426 
---
This PR implements the changes discussed in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/669#issuecomment-585549636 and in the comments on pb0GrA-oX.
<details><summary>Expand to see the history</summary>
<p>
I suspect that the original bug was that when the customer clicked on the PayPal buttons on the cart or product pages, while purchasing virtual goods, and returned to the store, if the customer didn't have the require billing address setting enabled on their PayPal Account, the customer would return with no data. No shipping (virtual), and no billing (not enabled). In that situation, the checkout fields would be essentially empty. 
If the customer tried to complete that purchase, the checkout would error because, by default, …

Only make the billing fields optional during an open PPEC session

---

assets/js/wc-gateway-ppec-generate-cart.js

**Issue**: #694 
---
Add custom `wc_ppec_validate_product_form` trigger where you can set the `.valid` property and override the result of `form.get( 0 ).checkValidity()`
1. You can check out what I'm doing here: https://wp-helgatheviking.codeanyapp.com/product/t-shirt-6-pack/
1. specifically here's my JS callback:
```
/**
* PayPal Express Smart buttons compatibility.
*/
$( document ).on( 'wc_ppec_validate_product_form', function( validity_check, $form ) {
var wc_mnm = $form.wc_get_mnm_script();
if ( 'object' === typeof wc_mnm ) {
validity_check.valid = wc_mnm.passes_validation();
}
})
```
Closes #694 .

"Filter" form validity via wc_ppec_validate_product_form event.

---

includes/class-wc-gateway-ppec-client.php

Fixes #485 
Description
---
Whenever a coupon is added to provide a discount, the Purchase details in the Paypal buyer account shows an extra item added "Line Item Amount Offset", equal to the discount amount and then eventually deducted as a Shipping Discount Amount: https://d.pr/i/unojiU
This extra line item amount offset was introduced to account for rounding variations between WC and PayPal, but this has been applying to all discounts, even if there is no rounding issue.
This total_item_amount includes the total of items and discounts and the difference is added as an extra line item. So, the first commit 8417ab5 does not include discounts in it (in both the cases of getting the details from the order and the cart).
The next commit a9cf763 makes appropriate modifications to the checks …

Do not add discounts to total item amount and cause line item amount offset

---

assets/js/wc-gateway-ppec-generate-cart.js
assets/js/wc-gateway-ppec-smart-payment-buttons.js
includes/class-wc-gateway-ppec-cart-handler.php

Per issue #558, when on a single product page containing an item that is out of
stock, both `wc-gateway-ppec-smart-payment-buttons.js` and
`wc-gateway-ppec-generate-cart.js` scripts throw exceptions as both
scripts are trying to target elements which don't exist when the product is out of stock:
From `wc-gateway-ppec-generate-cart.js`:
```
TypeError: Cannot read property 'checkValidity' of undefined
```
From `wc-gateway-ppec-smart-payment-buttons.js`:
```
Error: Document is ready and element #woo_pp_ec_button_product does not exist
```
From `master`:
1. Create an out-of-stock product.
2. Visit its single product page.
3. Check the browser console/source tabs
This PR adds a check for the relevant form element in each script and returns early if it is not present in the single product view. …

Exit early from js scripts before targeting nonexistent elements

---

assets/js/wc-gateway-ppec-settings.js
includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-settings.php
includes/settings/settings-ppec.php

**Issue**: #584 
---
While storing an API Certificate file, it is base64 encoded, but while retrieving it for use, it is not base64 decoded and so there are errors while using API certificate. 
1. Log into the Sandbox seller account at sandbox.paypal.com
1. Click on the gear icon on the top right and click on Account Settings.
1. Click on Update against API Access
1. Click on Manage API credentials under NVP/SOAP API integration (Classic)
1. If you already have API Signature here, remove it and request for an API Certificate. 
1. Download the API certificate, username and password. 
1. Go to the PPEC settings page from WooCommerce settings.
1. Use the API username and password just obtained. Choose the API Certificate file and then save.
1. On master, you should get "API Certificate not …

Use base64_decode on API certificate while creating Credential object

---

includes/class-wc-gateway-ppec-cart-handler.php

GitHub comment: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/668#issuecomment-604242940
---
When purchasing a subscription, you cannot use debit or credit card smart payment buttons because we need to create a billing agreement and therefore need a PayPal account. This PR hides credit and debit card fields when viewing a subscription product page or if the cart contains a subscription.
Unfortunately, the changes needed here were more than I would have liked. This is because of the way the `get_button_settings()` function sometimes gets an empty string or an array of hidden methods and so we needed to work around that. 
1. Set up your [PayPal Checkout settings](https://user-images.githubusercontent.com/8490476/77714957-0dc05c80-7026-11ea-8d86-a06b9b51a6a8. …

Hide debit/credit card SPBs for subscription purchases

---

includes/class-wc-gateway-ppec-admin-handler.php
includes/class-wc-gateway-ppec-checkout-handler.php

**Issue**: #700
---
When purchasing subscription products whose initial price is $0 (free trials etc) with PayPal Smart Buttons, when you return to the store, you aren't placed on the checkout with an active PayPal Session like you would when purchasing other products. This PR fixes that.
0. If you don't have one, create a subscription product with a free trial.
1. Go to the free trial product's single product page.
1. Click the PayPal (yellow) payment button.
1. Log in to PayPal and complete the steps.
1. When you return to the store:
- On `master` you will be placed on the normal checkout page where you will need to fill out the checkout, select a payment gateway etc.
- On this branch, you will be placed on the Pay for order special checkout page with only PPEC selected.
Completing the …

Fix free subscription initial purchases using PayPal Smart Buttons

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js

Per #708 when an invalid email is entered prior to selecting a PayPal button, the process fails and no error message is displayed for the user.
( From #708 )
1. Fill all the checkout fields (Name, Address, Postcode and ...) except Email
2. Fill the email field with an incorrect format like (test@test) or just (test)
3. Click on the PayPal button
4. You will see no errors appear and PayPal popup or new tab doesn't work.
After some digging, it looks like the reason for this is cases in which a non-empty invalid email is entered, [the response from our AJAX call in the spb script](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/49416711ebd4fcc3f945853d2856e71b528a4392/assets/js/wc-gateway-ppec-smart-payment-buttons.js#L123) is not structured as we expect.
What …

Check for response error message before assigning

---

changelog.txt
languages/woocommerce-gateway-paypal-express-checkout.pot
readme.txt
woocommerce-gateway-paypal-express-checkout.php

```
= 1.6.21 - 2020-04-14 =
* Fix - Ensure Puerto Rico and supported Locales are eligible for PayPal Credit. PR#693
* Fix - Support purchasing subscriptions with $0 initial payment - free trials, synced etc. PR#698
* Fix - Only make the billing fields optional during an active PayPal Checkout session. PR#697
* Fix - Uncaught JS errors on product page when viewing and out-of-stock product. PR#704
* Fix - Loading API certificates and improves managing certificate settings. PR#696
* Fix - Displaying PayPal Smart Payment buttons on pages with single product shortcode. PR#665
* Fix - Do not add discounts to total item amount and cause line item amount offset. PR#677
* Fix - Redirect to Confirm your PayPal Order page for subscriptions initial purchases using PayPal Smart Buttons. PR#702
* Fix - …
```

Release 1.6.21

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-checkout-handler.php
includes/class-wc-gateway-ppec-with-paypal-addons.php
includes/functions.php

**Issue**: #612
---
Whenever a Reference Transaction is done( via a renewal order of WC Subscriptions or a scheduled order of Autoship ) the transaction details are not stored in `_woo_pp_txnData` meta like it is done with Express Checkout. Because of this, the Reference Transaction orders throw errors while refund.
To fix this, the details required for refund are saved in the `_woo_pp_txnData`  meta for Reference Transactions too.
1. Create a subscription product and purchase it.
1. Try to refund the parent order. This should fo through without any issues.
1. Now, process a renewal order on the subscription. 
1. Try to refund the renewal order. On this branch, it will go through but on any other branch, it will throw an error.
1. Also note that the renewal order has an entry for …

Save transaction data of Reference transactions in _woo_pp_txnData meta

---

assets/js/wc-gateway-ppec-settings.js
includes/abstracts/abstract-wc-gateway-ppec.php
includes/settings/settings-ppec.php

**Issue**: #706 
---
API Credential validation was pretty confusing and imo not complete. It only started validating if you entered a username. This meant if you added just a signature, it would save without any error being displayed. 
With this PR, the idea is that validation starts if any API credential is added. 
1. Go to **WooCommerce > Settings > Payments > PayPal Checkout**
1. Make a note of your existing credentials. 
1. Remove all credentials except for your signature and **Save**.
1. On `master` you'll notice two things:
- You don't get any error message. Just a notice saying your [settings were saved](https://user-images.githubusercontent.com/8490476/78846699-f20a7c80-7a4f-11ea-9d3f-4bcf2674953b.png).
- If you scroll down to the credentials, you'll also notice that the [fields …

Validate incomplete API credentials fields

---

includes/class-wc-gateway-ppec-checkout-handler.php

**Issues**: #722 and #724
---
When you try to purchase a product with PP from the product/cart page and set your country to Cyprus, when you return from PayPal and try to place the order, you'll get a "Billing State/County is a required field" error.
To explain... when you set your country to Cyprus in PayPal checkout, the address fields don't have a state field and only requires a city to be filled in: https://d.pr/i/B0n9wX
On the WooCommerce side, we do include a State field for Cyprus and it's set as required: https://d.pr/i/FGmyzM
While digging through the code I noticed we have a line of code that makes the [State field optional while on the "confirm your Paypal order" page](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/06ae4cecdb9c3c976d3ba2dcbe7237e …

Fixes "Billing State / County is a required field." error on Confirm your PayPal Order page

---

assets/js/wc-gateway-ppec-generate-cart.js

Per #515, when attempting to pay with PayPal from product page where products are missing required or variable fields, the PPEC buttons don't trigger the same behaviors as the default WC Add To Cart button. This leads to some disconnect between the two, and a somewhat awkward experience for the user.
1. Create a new required field (Multiple Choice/Radio Buttons) for all products with WooCommerce Product Add-ons extension
2. From the front-end, visit a simple product page and select either of the PayPal buttons. Nothing will happen
3. Select the Add to cart button. You should see an HTML form validation popup
4. Visit a variable product page, and select either PP button (without modifying the product form). Again, nothing will happen
5. Select the Add to cart button. You should see some …

Allow WC to perform validation when missing fields

---

includes/class-wc-gateway-ppec-with-spb-addons.php
includes/class-wc-gateway-ppec-with-spb.php

**Issue**: #718
---
In PHP versions 5.4 and above, a PHP warning is thrown when you try to set `$session->{value}` when `$session` is `null`.
This PR removes these warnings by sending a default return value when calling `WC()->session->get( 'PayPal' )` when a session doesn't exist.
Closes #718

Fixes "PHP Warning: Creating default object from empty value" when a PayPal session doesn't exist

---

includes/class-wc-gateway-ppec-cart-handler.php

**Slack thread**: https://a8c.slack.com/archives/CJTS771PB/p1588918039373700
---
When the store's base currency is set to AUD (and possibly other currencies), clicking the new SPBs leads to a console log error. See below.
1. Set your store's base currency to AUD https://cloudup.com/cf9Z4m3JjOO
1. Go to a product page and click the new PayPal SDK SPB.
1. On `2.0_dev` the modal will pop up and then close with the following errors in the console log. 
2. On this branch, the modal displays correctly and payment can be taken.

Pass store currency to SDK SPB args

---

includes/class-wc-gateway-ppec-settings.php

Fixes #480 
**Description**
When the WP locale does not have an exact equivalent PayPal locale, the PayPal checkout process defaults to _en_US_. While this is acceptable for certain cases, there are cases where a locales mapping can give a better choice for PayPal locale.
Firstly, there are more [supported locale codes](https://developer.paypal.com/docs/api/reference/locale-codes/#supported-locale-codes)(34) by PayPal now than in the master branch(24). I have added these. 
One of the existing locale codes, _tr_TR_ is not in the list of supported locale codes. So, I have removed it. I am not certain about this.
I have added a locales_mapping that maps WP locale codes to PayPal locale codes for some of the obvious cases.
**Steps to Test**
1. In the WordPress General Settings, change the …

Add locales and mapping

---

readme.txt
woocommerce-gateway-paypal-express-checkout.php

Adds a `Requires PHP` flag and updates the WC and WP tested up to versions.
Closes #701, closes #715, closes #608

Add PHP version requirement and update WP and WC tested up to versions

---

includes/class-wc-gateway-ppec-settings.php

**Issue**: #733
---
PayPal's [locale docs](https://developer.paypal.com/docs/api/reference/locale-codes/#supported-locale-codes) list `en_US` as the code to use for Canadian English, however, this means when customers choose to pay with a credit card, the default address is US. After some testing, it appears the docs are incorrect and using `en_CA` works.
1. In your sites, general settings set the language to English Canada (https://cloudup.com/cVrqnwcOGmF)
1. Add a product to the cart and proceed to checkout. 
1. Click the credit card Smart Payment Button.
1. On `master` you'll notice US is the default address. https://cloudup.com/cejsTyhAPwC
2. On this branch the address is Canada by default. https://cloudup.com/cpMNOlYRfeO
1. I also tested using the legacy JS and it works there too. …

Add en_CA to the list of PayPal supported locales

---

includes/class-wc-gateway-ppec-plugin.php

Move `Docs` link from action section to meta section and add `Support` link to the meta section.
Closes #735.
1. Check out featured branch 
2. Add plugin to testing site
3. Activate plugin
4. Look up links on plugin page
**Before:**
**After:**
> Update - Move `Docs` link from action section to meta section and add `Support` link to the meta section.

#735: Update plugin links

---

includes/class-wc-gateway-ppec-settings.php

Similar to #734.
In #536, the customer specifically requests adding support for New Zealand locale code but this was not added in #658.
As @menakas mentions in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/734#issuecomment-633331430, there are still some new locales we can add support for now that we're using the latest SDK, but let's not hold off releasing 2.0 because of this.
We can do a v2.1 in the next few weeks to add the rest :)

Add en_NZ to the list of PayPal supported locales

---

changelog.txt
languages/woocommerce-gateway-paypal-express-checkout.pot
readme.txt
woocommerce-gateway-paypal-express-checkout.php

```
= 2.0.0 - 2020-05-25 =
* New - Upgrade to the latest PayPal Checkout Javascript SDK. PR#668
* Add - New setting found under Button Styles for choosing a Smart Payment Button label. PR#666
* Add - Support for more locales. PR#658
* Fix - Display Smart Payment Buttons on Product pages built from a shortcode. PR#665
* Fix - Send the product SKU to PayPal so it's displayed in the order/transaction details and reports on PayPal. PR#664
* Fix - Show an error when saving incomplete/missing API credentials. PR#712
* Fix - Remove PHP warnings in later versions of PHP when a PayPal Session doesn't exist. PR#727
* Fix - Error when processing refunds (Already Refunded. No Amount to Refund). PR#710
* Fix - Required state field errors on the "Confirm your PayPal Order" page when returning from …
```

Release 2.0.0

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js
includes/class-wc-gateway-ppec-cart-handler.php

**Issue**: #739 
**Ticket**: https://wordpress.org/support/topic/latest-version-has-js-critical-error/
---
Customers have reported that after upgrading to 2.0.0 their PayPal buttons aren't loading and they're seeing the following console/javascript errors:
```
Uncaught TypeError: paypal.getFundingSources is not a function
at render (wc-gateway-ppec-smart-payment-buttons.js:208)
at HTMLBodyElement.dispatch (jquery.js:3)
at HTMLBodyElement.r.handle (jquery.js:3)
at Object.trigger (jquery.js:3)
at Object.a.event.trigger (jquery-migrate.min.js:2)
at HTMLBodyElement.<anonymous> (jquery.js:3)
at Function.each (jquery.js:2)
at a.fn.init.each (jquery.js:2)
at a.fn.init.trigger (jquery.js:3)
at Object.success (checkout.min.js:1)
```
I discovered that this issue is being caused by the old …

Fixes `paypal.getFundingSources is not a function` console errors

---

changelog.txt
languages/woocommerce-gateway-paypal-express-checkout.pot
readme.txt
woocommerce-gateway-paypal-express-checkout.php

```
* Fix - PayPal buttons not loading on the page, accompanied with the javascript/console error: "paypal.getFundingSources (or paypal.Buttons) is not a function". PR#740
```

Release 2.0.1

---

includes/class-wc-gateway-ppec-cart-handler.php

**Issue**: #750 
**Ticket**: 3007850-zen
---
The checkout is currently broken when you set the Payment Action in PPEC settings to Authorize.
With the new `sdk/js` we must set the [intent query-parameter](https://developer.paypal.com/docs/checkout/reference/customize-sdk/#intent) when loading the payment form otherwise PayPal defaults to capture and then throws and error when trying to place the order.
From my understanding, in 1.6.21 we never had to set an intent when loading the from with `checkout.js` because we handled authorization in later API requests once we received a token from PayPal, but with the new sdk we need to.
1. Set the payment action settings to Authorize: https://d.pr/i/2ONQis
1. Visit checkout page
1. Try click PayPal button and notice a JS error
Closes #750

Fix JS errors when Payment Action is set to Authorize

---

assets/css/wc-gateway-ppec-frontend.css
includes/class-wc-gateway-ppec-cart-handler.php

**Issue**: #747
---
This PR updates our cart checkout button separator so we're consistent. 
Before and after:
1. Checkout this branch. 
2. Enable checkout buttons on the cart page.
1. _Optional_: enable Stripe's checkout buttons. This may require more set up than it's worth. I can;'t recall how to do it exactly. I think you need a card stored in your google wallet or something 🤷‍♂️  
1. On the cart page notice the - or - has been replaced with - OR - to be consistent with other gateways. 
Closes #747

Update checkout buttons separator to be consistent

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/functions.php

Refunds did not save to database with WC_versions over 3.0 due to missing code.
The method got updated but not saved to the database.
1. Place an order with paypal as payment method.
2. Check database table meta-data for _woo_pp_txnData -> refunded_amount (is 0)
3. Do a partial or complete paypal refund
4. Check database table meta-data for _woo_pp_txnData -> refunded_amount
Closes # .

save order-data to database

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js
includes/class-wc-gateway-ppec-cart-handler.php

**Issue**: #757 
---
In 2.0 we changed the behaviour so that when a customer closes/cancels the PayPal modal they're now always redirected to the cart page.
There are a few instances where this change feels a bit odd from a customer's perspective. Some examples:
- you have filled in the checkout address forms, selected shipping, click the PayPal button, decide you wanted to pay with Stripe, close the PayPal window and are redirected to the cart page.
- you are browsing a product page and click the PayPal button, decide you don't want to go ahead with the order, close the window and get redirected to the cart page.
This also feels a bit weird if your store doesn't use a cart page (i.e. empty Cart page in *WooCommerce > Settings > Advanced*) and customers are redirected back to stores home …

Don't always redirect the customer to the cart page after closing PayPal modal

---

includes/class-wc-gateway-ppec-cart-handler.php

See #762 for the original PR that was opened and then not long after, closed by the author.
I found this user has opened a ticket on WP.org as well: https://wordpress.org/support/topic/can-i-checkout-through-paypal-instead-of-redirect/
I can understand why people may want to filter the script args so they can change some of the values we set like: `locale`, `currency` and `commit`, or even set any parameters we're not using (see more details on all available script args in the PayPal docs on [Customising the PayPal JavaScript SDK Script](https://developer.paypal.com/docs/checkout/reference/customize-sdk/#query-parameters))
This PR is similar to #762 except I've added a few extra args to the filter to include: `$client` and `$settings`.

Make the SDK script args filterable

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js

While investigating #759 I came across this issue: when the button layout is set to "Vertical" and at least one funding method needs to be hidden (including PayPal Credit), the buttons seem to "think" they're being rendered in a "horizontal" layout (as reflected by the CSS classes attached to the containers), even though they're actually being presented in a vertical one.
This is because we're rendering all eligible buttons using what PayPal calls "[standalone buttons](https://developer.paypal.com/docs/checkout/integration-features/standalone-buttons/)" and not passing the layout to the SDK except when taking care of the main PayPal button. We did this because not all style properties are supported by all buttons, but "layout" does seem to be supported in all scenarios.
This is probably a …

Preserve layout style setting when using standalone buttons

---

includes/settings/settings-ppec.php

PayPal doesn't support disabling mobile number field for direct
Debit or Credit Card Payments. Added a note to the field description
to indicate the same. I don't think a documentation change is required
for this change
**Issue**: #770 
Closes #770

Modified field description for Require Phone Number

---

assets/js/wc-gateway-ppec-smart-payment-buttons.js

**Issue**: #773.
**TL;DR**: The [`fetch()` API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) we're using [in our Smart Payment Buttons JavaScript code](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/2631a8bc6433a9a0c857a73a7b887a0986d27eb7/assets/js/wc-gateway-ppec-smart-payment-buttons.js#L142-L150) to call the "start checkout" AJAX action when the PayPal button is clicked has an implicit value of "same-origin" for its "credentials" setting, which controls whether the request includes cookies with session/auth information as part of it or not. Before Aug 2017, the default value for this setting was "omit" which sent nothing, so browsers released before Aug 2017 or those that weren't updated, perform this request anonymously, …

Explicitly set 'same-origin' policy for `fetch()` (fixes compat with old browsers)

---

includes/abstracts/abstract-wc-gateway-ppec.php
includes/class-wc-gateway-ppec-client.php

This fixes https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/416. 
- This defines image sizes for `ppec_logo_image_size` as 190x60 and `ppec_header_image_size` as 750x90 using [add_image_size](https://developer.wordpress.org/reference/functions/add_image_size/) function.
- Then renders the image based on this condition: `'logo_image_url' === $key ? 'ppec_logo_image_size' : 'ppec_header_image_size' `.
1. Switch to the master/main branch.
1. Use the browser in full-screen (otherwise PayPal window will be too short to display the logo image).
1. Checkout using PPEC, you will see a cropped image.
1. Switch to the branch `issue_416`, try checking out again, you will see the image in proper width. Checkout the screenshots below for a before and after.
- This PR …

Display correct image size in the PayPal Checkout window

---

.travis.yml
readme.txt

This renames all references of "master" branch to "main" as part of our efforts
to rename master for all of our repos.
See pb0GrA-R4-p2

Rename instances of master to main
